Repository YadavAkhileshh/Alien-Invasion-Defense, pull requests merged in 2024-10, with the labels that each got.

#31 Adding dropdown menu to how to play
  Alien.css
  index.html
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#116 ✨issue #109 solved✨
  Alien.css
  index.html
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#247 added welcome page
  spacemusic.mp3
  spaceship.webp
  style.css
  welcome1.html
Labels: gssoc-ext, hacktoberfest-accepted, Level2

#232 SignUp and Login Form Updation and Enhancement | #Issue 183
  index.html
  login/login.css
  login/login.html
  signup/signup.css
  signup/signup.html
Labels: Level3

#553 making the game run
  Alien.js
  index.html
Labels: level3
